"""Shared AgentState schema flowing through every LangGraph node."""

from __future__ import annotations

from typing import Annotated

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class AgentState(TypedDict):
    """State object passed between all nodes in the pipeline graph.

    Fields
    ------
    query:
        The raw user query string.
    intent:
        Routing decision produced by the Router Agent.
        One of ``"conceptual"`` or ``"implementation"``.
    retrieved_chunks:
        List of chunk dicts returned by FAISS retrieval.  Each dict has at
        least the keys ``text``, ``chunk_type``, ``source_file``,
        ``header_path``, and ``language``.
    response:
        The final answer generated by either the Conceptual or Implementation
        Agent.
    messages:
        Full conversation history maintained by LangGraph's ``add_messages``
        reducer so that successive turns accumulate correctly.
    """

    query: str
    intent: str
    retrieved_chunks: list[dict]
    response: str
    messages: Annotated[list[BaseMessage], add_messages]
